version: '3'
services:
    app:
        build: .
        container_name: app-filament-demo
        entrypoint: ./.docker/entrypoint.sh
        volumes:
            - .:/var/www
        networks:
            - app-network
    nginx:
        build: .docker/nginx
        entrypoint: sh /var/www/.docker/nginx/entrypoint.sh
        container_name: nginx-app-filament-demo
        restart: always
        tty: true
        environment:
            - APP_HOST=app
            - APP_PORT=9000
        ports:
            - 8000:80
        volumes:
            - .:/var/www
        links:
            - app
        networks:
            - app-network
    redis:
        image: redis:alpine
        expose:
        - 6379
        networks:
        - app-network
networks:
    app-network:
        driver: bridge
